"""Static-site build — Markdown posts -> HTML, no external dependencies.

Minimal renderer (headings, bold, paragraphs) adapted from the pattern in the existing
website-static-html-*.com repos. Enough for the slice; NOT a general blogging engine.
"""

from __future__ import annotations

import html
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
POSTS = ROOT / "content" / "posts"
SITE = ROOT / "docs"  # GitHub Pages "deploy from branch" serves main:/docs

PAGE = """<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
 body{{max-width:44rem;margin:3rem auto;padding:0 1.2rem;font:17px/1.65 -apple-system,Segoe UI,Roboto,sans-serif;color:#1a1a1a;background:#fafafa}}
 h1{{font-size:1.9rem;line-height:1.2}} h2{{margin-top:2rem}} a{{color:#c0392b}}
 .meta{{color:#777;font-size:.9rem;margin-bottom:2rem}} .gen{{color:#999;font-size:.8rem;margin-top:3rem;border-top:1px solid #e2e2e2;padding-top:1rem}}
</style></head><body>
{body}
<p class="gen">{gen}</p>
</body></html>
"""


def parse(md: str) -> tuple[dict, str]:
    fm: dict[str, str] = {}
    body = md
    if md.startswith("---"):
        _, block, body = md.split("---", 2)
        for line in block.strip().splitlines():
            k, _, v = line.partition(":")
            fm[k.strip()] = v.strip().strip('"')
    return fm, body.strip()


def render(body: str) -> str:
    out: list[str] = []
    for para in re.split(r"\n\s*\n", body):
        p = para.strip()
        if not p:
            continue
        if p.startswith("## "):
            out.append(f"<h2>{html.escape(p[3:])}</h2>")
        elif p.startswith("# "):
            out.append(f"<h1>{html.escape(p[2:])}</h1>")
        else:
            esc = html.escape(p)
            esc = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", esc)
            out.append(f"<p>{esc}</p>")
    return "\n".join(out)


def main() -> int:
    SITE.mkdir(exist_ok=True)
    cards = []
    for md in sorted(POSTS.glob("*.md")):
        fm, body = parse(md.read_text())
        slug = md.stem
        page = PAGE.format(
            title=html.escape(fm.get("title", slug)),
            body=render(body),
            gen=html.escape(f"Generated by {fm.get('generated_by', 'n/a')} · {fm.get('date', '')}"),
        )
        (SITE / f"{slug}.html").write_text(page)
        cards.append(f'<li><a href="{slug}.html">{html.escape(fm.get("title", slug))}</a><br>'
                     f'<span class="meta">{html.escape(fm.get("summary", ""))}</span></li>')
    index = PAGE.format(
        title="The Spark Engineering Story",
        body="<h1>The Spark Engineering Story</h1><p class='meta'>Building the machine that "
        "builds the machine — notes from the factory.</p><ul>" + "".join(cards) + "</ul>",
        gen="Published via the Spark factory (Product 1).",
    )
    (SITE / "index.html").write_text(index)
    print(f"Built {len(cards)} post(s) -> {SITE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
